const productData = [
  {
    id: 1,
    image: "/images/img1.webp",
    smallImage: "/smalimages/s1.webp",
    secImage: "/images/img-1.webp",
    productDesc: "Cropped Stay Groovy off white",
    cardDesc: "X | White T-shirt",
    currency: "$",
    price: 19.9,
    text: "Or 9",
    sale: "x$1.21",
    quantity: 1,
    size: ["X", "L", "XL", "XXL"],
  },
  {
    id: 2,
    image: "/images/img2.webp",
    smallImage: "/smalimages/s2.webp",
    secImage: "/images/img-2.webp",
    productDesc: "Basic Cactus White T-shirt",
    cardDesc: "X | Wine",
    currency: "$",
    price: 13.25,
    text: "or 3",
    sale: "x$4.42",
    quantity: 1,
    size: ["X", "ML", "L"],
  },
  {
    id: 3,
    image: "/images/img3.webp",
    smallImage: "/smalimages/s3.webp",
    secImage: "/images/img-3.webp",
    productDesc: "Skater Black Sweatshirt",
    cardDesc: "XL | Tony Hawk",
    currency: "$",
    price: 25.9,
    text: "or 12",
    sale: "x$2.16",
    quantity: 1,
    size: ["XL"],
  },
  {
    id: 4,
    image: "/images/img4.webp",
    smallImage: "/smalimages/s4.webp",
    secImage: "/images/img-4.webp",
    productDesc: "Black Tule Oversized",
    cardDesc: "M | Tule",
    currency: "$",
    price: 29.45,
    text: "Or 5",
    sale: "x$5.89",
    quantity: 1,
    size: ["M", "ML"],
  },
  {
    id: 5,
    image: "/images/img5.webp",
    smallImage: "/smalimages/s5.webp",
    secImage: "/images/img-5.webp",
    productDesc: "Black Batman T-shirt",
    cardDesc: "S | Really Cool T-shirt",
    currency: "$",
    price: 10.9,
    text: "Or 9",
    sale: "x$1.21",
    quantity: 1,
    size: ["XS", "S"],
  },
  {
    id: 6,
    image: "/images/img6.webp",
    smallImage: "/smalimages/s6.webp",
    secImage: "/images/img-6.webp",
    productDesc: "Blue T-Shirt",
    cardDesc: "X | Mark Zuck have 365 of this one",
    currency: "$",
    price: 9.0,
    text: "Or 3",
    sale: "x$3.00",
    quantity: 1,
    size: ["X", "L", "XL"],
  },
  {
    id: 7,
    image: "/images/img7.webp",
    smallImage: "/smalimages/s7.webp",
    secImage: "/images/img-7.webp",
    productDesc: "Loose Black T-shirt",
    cardDesc: "X |",
    currency: "$",
    price: 14.0,
    text: "Or 5",
    sale: "x$2.80",
    quantity: 1,
    size: ["X", "L", "XL", "XXL"],
  },
  {
    id: 8,
    image: "/images/img8.webp",
    smallImage: "/smalimages/s8.webp",
    secImage: "/images/img-8.webp",
    productDesc: "Ringer Hall Pass",
    cardDesc: "X | White T-shirt",
    currency: "$",
    price: 10.9,
    text: "Or 9",
    sale: "x$1.21",
    quantity: 1,
    size: ["X", "L", "XL", "XXL"],
  },
  {
    id: 9,
    image: "/images/img9.webp",
    smallImage: "/smalimages/s9.webp",
    secImage: "/images/img-9.webp",
    productDesc: "Grey T-shirts",
    cardDesc: "X | You will like this one",
    currency: "$",
    price: 14.9,
    text: "Or 7",
    sale: "x$2.13",
    quantity: 1,
    size: ["X", "L"],
  },
  {
    id: 10,
    image: "/images/img10.webp",
    smallImage: "/smalimages/s10.webp",
    secImage: "/images/img-10.webp",
    productDesc: "Black T-shirt with white stripes",
    cardDesc: "X | Adidas originals",
    currency: "$",
    price: 14.9,
    text: "Or 7",
    sale: "x$2.13",
    quantity: 1,
    size: ["X", "L"],
  },
  {
    id: 11,
    image: "/images/img11.webp",
    smallImage: "/smalimages/s11.webp",
    secImage: "/images/img-11.webp",
    productDesc: "Turtles Ninja T-shirt",
    cardDesc: "X | Cowabunga!",
    currency: "$",
    price: 10.9,
    text: "Or 9",
    sale: "x$1.21",
    quantity: 1,
    size: ["X", "L", "XL"],
  },
  {
    id: 12,
    image: "/images/img12.webp",
    smallImage: "/smalimages/s12.webp",
    secImage: "/images/img-12.webp",
    productDesc: "Slim black T-shirt",
    cardDesc: "XL | When you wish well",
    currency: "$",
    price: 49.9,
    text: "Or 8",
    sale: "x$2.16",
    quantity: 1,
    size: ["XL", "XXL"],
  },
  {
    id: 13,
    image: "/images/img13.webp",
    smallImage: "/smalimages/s13.webp",
    secImage: "/images/img-13.webp",
    productDesc: "Blue Sweatshirt",
    cardDesc: "S | Very comfy",
    currency: "$",
    price: 22.5,
    text: "Or 4",
    sale: "x$5.63",
    quantity: 1,
    size: ["S"],
  },
  {
    id: 14,
    image: "/images/img14.webp",
    smallImage: "/smalimages/s14.webp",
    secImage: "/images/img-14.webp",
    productDesc: "White T-shirt Gucci",
    cardDesc: "XL | Girl the future is all your",
    currency: "$",
    price: 18.7,
    text: "Or 4",
    sale: "x$4.67",
    quantity: 1,
    size: ["XL"],
  },
  {
    id: 15,
    image: "/images/img15.webp",
    smallImage: "/smalimages/s15.webp",
    secImage: "/images/img-15.webp",
    productDesc: "Tropical Wine T-shirt",
    cardDesc: "L |",
    currency: "$",
    price: 134.9,
    text: "Or 5",
    sale: "x$26.98",
    quantity: 1,
    size: ["L", "XL"],
  },
  {
    id: 16,
    image: "/images/img16.webp",
    secImage: "/images/img-16.webp",
    smallImage: "/smalimages/s16.webp",
    productDesc: "Marine Blue T-shirt",
    cardDesc: "L |",
    currency: "$",
    price: 49.0,
    text: "Or 9",
    sale: "x$5.44",
    quantity: 1,
    size: ["L", "XL"],
  },
];

export default productData;
